//cabeçalho da função usada no arquivo.c
char telaRelatorio(void);
char moduloRelatorio (void);
char relatorioLocalArmaz(void);
char relatoriopeloTipo(void);
char relatorioCategoria(void);
void escRelatoriosCategoria(void);
void escRelatoriosLocal(void);
void escRelatoriosTipo(void);
int exibirItensHigiene(void);
int exibirItensLimpeza(void);
int exibirItensAlimento(void);
//int exibirEntrada(void);
//int exibirSaida(void);
int exibirGeladeira(void);
int exibirArmarioCozinha(void);
int exibirAreaServ(void);
int exibirGuardaRoupa(void);
int exibirBanheiro(void);
NoItem* listaOrdenadaItens(void);
void exibeOrdemItem(NoItem* lista);