int validarLetras(char letra[], int tamanho);
int lerLetras(char nome[]);
//int lerUsername(char username[]);
int lerQuantidade(char numero[]);
void deixarTelaLimpa(void);
int valida_data(int dia, int mes, int ano);
int lerEmail(char email[]);
int tamanhoString(char a[]);
int charParaInt(char *num);
int poten(int num, int pot);
int lerUsername(char username[]); 
