int validateLetters(char letra[], int tamanho);
int lerLetras(char nome[]);
int readQuantity(char numero[]);
void deixarTelaLimpa(void);
int valida_data(int dia, int mes, int ano);
int readEmail(char email[]);
int stringLength(char a[]);
 int charToInt(char *num);
int poten(int num, int pot);
int readUsername(char username[]); 
char* verDiaMesAno(void);
char* dividPal(char *pal, int del1, int del2);
